"""bug fix

Revision ID: 984d77b2a0b3
Revises: ce88bc75e9fc
Create Date: 2023-10-19 23:06:12.785720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '984d77b2a0b3'
down_revision: Union[str, None] = 'ce88bc75e9fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_chatbot_id_unique', 'chat_messages', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_chatbot_id_unique', 'chat_messages', ['user_ref', 'chatbot_id'])
    # ### end Alembic commands ###
